// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import frc.robot.CommonLogic;
import frc.robot.Robot;

/**
 *
 */
 public class Auto_DriveByGyro extends Command {

    
    double inches = 0;
    public Auto_DriveByGyro(double dist_inches, int heading_deg) {
        inches = dist_inches;

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
      Robot.subChassis.smartMotion_activate(inches);

    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {

        Robot.subChassis.smartMotion_steerStraight();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
